homepage/urls.py
from django.urls import path
from .views import home, logoutuser

app_name = 'homepage'

urlpatterns = [
    path('', home, name='home'),
    path('/logout/', logoutuser, name='logout'),
]

pepewrangers/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
import registerpage.urls as registerpageUrls
import landingpage.views as landingview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='landingpage/'), name='landingpage'),
    path('hello/', include('hello_world.urls')),
    path('landingpage/', include('landingpage.urls')),
    path('register/', include('registerpage.urls'), name='registerpage'),
    path('logout/', landingview.logoutuser, name = 'logout'),
    path('home/', include('homepage.urls')),
    path('programs/', include('programs.urls')),
    path('daftar_donasi/', include('daftar_donasi.urls'), name='daftar_donasi'),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('testimonipage/', include('testimonipage.urls')),

]

registerpage/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "registerpage"

urlpatterns = [
    path('', views.show_and_process_register_page, name='registerpage'),
    # path('process/', views.register_form_process, name='register_form_process'),
    # path('process/404/', views.show_404,name='show404'),
    # path('landing/', views.index, name='index'),
    # path('process/', views.submit_message, name = 'form_process'),
    # path('profile/', views.showprofile, name = 'profile'),
]

registerpage/models.py
from django.db import models

class Donatur(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateTimeField()
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.email
# Create your models here.

registerpage/forms.py
from django import forms

class RegisterForm(forms.Form):
    attrs = {'class':'form-control'}
    attrs_date = {'type':'date'}
    attrs_time = {'type':'time'}
    name = forms.CharField(label='Your Name', max_length=50, required=True,
        widget=forms.TextInput(attrs=attrs))
    birthdate = forms.DateField(label='Birtday Date', required=False,
        widget=forms.DateInput(attrs={**attrs, **attrs_date}))
    email = forms.CharField(label='Email', max_length=100, required=True,
        widget=forms.EmailInput(attrs=attrs))
    password = forms.CharField(label='Password', max_length=75, required=True,
        widget=forms.PasswordInput(attrs=attrs))

registerpage/views.py
from django.shortcuts import render, redirect
# from django.http import HttpRedirect
from .forms import RegisterForm
from .models import Donatur

response = {}

def show_and_process_register_page(request):
    response['registform'] = RegisterForm()
    response['errormessage'] = ''
    form = RegisterForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['birthdate'] = request.POST['birthdate']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        donatur = Donatur(
            name = response['name'],
            email = response['email'],
            birthdate = response['birthdate'],
            password = response['password']
            )
        try:
            donatur.save()
        except Exception:
            response['errormessage'] = 'This email is already taken'
            return render(request,'registerpage.html', response)
            #/register #/404 #/404 register/404
        return redirect('/home/')
    return render(request, 'registerpage.html', response)


# def show_register_page(request):
#     response['registform'] = RegisterForm()
#     return render(request, 'registerpage.html',response)

# def register_form_process(request):
#     form = RegisterForm(request.POST or None)
#     if(request.method == 'POST' and form.is_valid()):
#         response['name'] = request.POST['name']
#         response['birthdate'] = request.POST['birthdate']
#         response['email'] = request.POST['email']
#         response['password'] = request.POST['password']
#         donatur = Donatur(
#             name = response['name'],
#             email = response['email'],
#             birthdate = response['birthdate'],
#             password = response['password']
#             )
#         try:
#             donatur.save()
#         except Exception:
#             response['errormessage'] = 'This email is already taken'
#             return render(request,'registerpage.html', response)
#             #/register #/404 #/404 register/404
#         return redirect('/home/')
#     else:
#         return r edirect('/')

# def show_404(request):
#     return render(request, '404.html',response)
# Create your views here.

registerpage/templates/registerpage.html
<head>
    {%load static%}
    <title>Sinar Perak</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "registerpage.css" %}">
</head>

<body id = 'main'>
    <nav class="navbar navbar-expand-lg navbar-dark" id="navigasi">
        <div class="container">
            <p class="navbar-brand" id="merek">Sinar Perak</p>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class='container'>
        <div id='pagetitle'>Form Pendaftaran</div>
        <form id="form" method="POST" action="{% url 'registerpage:registerpage' %}">
            {%csrf_token%}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <strong>{{registform.name.label_tag}}</strong>
                    {{registform.name}}
                </div>
                <div class="form-group col-md-6">
                    <strong>{{registform.birthdate.label_tag}}</strong>
                    {{registform.birthdate}}
                </div>
            </div>
            <div class="form-group">
                <strong>{{registform.email.label_tag}}</strong>
                {{registform.email}}
                {{errormessage}}
            </div>
            <div class="form-group">
                <strong>{{registform.password.label_tag}}</strong>
                {{registform.password}}
            </div>
        </form>
        <button type="submit" , class="btn btn-dark" , form="form" , value="Submit">Daftar</button>
    </div>
</body>