homepage/urls.py
from django.urls import path
from .views import home, logoutuser

app_name = 'homepage'

urlpatterns = [
    path('', home, name='home'),
    path('/logout/', logoutuser, name='logout'),
]

pepewrangers/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
import registerpage.urls as registerpageUrls
import landingpage.views as landingview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='landingpage/'), name='landingpage'),
    path('hello/', include('hello_world.urls')),
    path('landingpage/', include('landingpage.urls')),
    path('register/', include('registerpage.urls'), name='registerpage'),
    path('logout/', landingview.logoutuser, name = 'logout'),
    path('home/', include('homepage.urls')),
    path('programs/', include('programs.urls')),
    path('daftar_donasi/', include('daftar_donasi.urls'), name='daftar_donasi'),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('testimonipage/', include('testimonipage.urls')),

]

testimonipage/urls.py
from django.conf.urls import url
from django.urls import include, path
from .views import about, addComment

app_name = "about"

urlpatterns = [
	path('', about , name='about'),
	path('addComment', addComment , name='addComment'),
]

testimonipage/models.py
from django.db import models
from datetime import datetime,date
from django.utils import timezone


class Testimoni(models.Model):
	username = models.CharField(max_length=100)
	comment = models.CharField(max_length=500, null=True)
	time = models.DateTimeField(auto_now_add = True, null = True, blank = True)

testimonipage/forms.py
from django import forms

class Comment(forms.Form):
	testimoni_komentar = forms.CharField(label="Tuliskan komentar anda tentang kami", required=True)

testimonipage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from .models import Testimoni
from .forms import Comment

def about(request):
	response = {}

	form = Comment(request.POST or None)
	CommentUser = Testimoni.objects.all()
	response = {
		"form" : form, 
		"CommentUser" : CommentUser,
	}
	return render(request, "about.html", response)

def addComment(request):
	form = Comment(request.POST)
	print('added')

	if (request.method == 'POST'):
		print('posted')
		if(form.is_valid()):
			print('valid')
			message = request.POST["testimoni_komentar"]
			testi = Testimoni(comment = message, username = "User")
			testi.save()
	return redirect('about:about') 

testimonipage/templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Tentang Kami</title>
  <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Istok+Web:700|Karla:400,700" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="icon" href="https://image.ibb.co/nhxWkf/HAND-MADE-2.png" type="image/x-icon" />

</head>

<style>


  .col-md-12{
    background-color: rgb(86,86,86);
    background-color: rgba(86,86,86, 0.7);
    border-radius: 20px; 
    margin-top: 20px;
    text-align: center;
    margin: auto;
    padding-top: 20px;
    padding-bottom: 30px;
    padding-right: 30px;
    color: white;
  }
  .col-md-11{
    background-color: rgb(255,255,255);
    background-color: rgba(255,255,255, 0.7);
    margin-top: 20px;
    margin: auto;
    text-align: center;
    padding-top: 20px;
    padding-bottom: 30px;
    padding-right: 30px;
    color: black;
  }

  .container-fluid{
    font-family: 'Bitter', serif;
  }

  .container{
    font-family: 'Bitter', serif;
  }


  .copyright{
    padding-top: 10px;
    font-family: 'Roboto', sans-serif;
    color: black;
    }

  footer {
    background-color: #CBCACA;
    color: white;
    max-height: 90px;
  }
  h4{
    width: 70%;
    margin: auto;
  }

</style>
<body style="background-color: #CBCACA">

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="/home/">Sinar Perak</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/daftar_donasi/">Daftar Donasi</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Testimoni</a>
    </li>
    <li class="nav-item">
      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
       {% else %}
      <a class="nav-link" href="#">Log Out</a>
       {% endif %}
    </li>
  </ul>
</nav>

    <div class="container-fluid text-center">
      <br>
        <h1>Tentang Kami</h1>
        <br>
          <h4>Untuk Mereka (UM) mengembangkan sebuah platform yang bergerak di bidang sosial. Kami bekerja sama untuk menciptakan awareness masyarakat terhadap bencana nasional. Untuk itu bantu kami menciptakan indonesia yang sejahtera</h4>
          <br>
          <br>

      <div class="container">
      <div class="row">
        <div class="col-sm">
            <center>
                <img src="" class="rounded-circle" width=200px height=200px>
              </center>
          <br>
          <h3>Nadhirsyah</h3>
          <h5>Founder</h5>
        </div>

        <div class="col-sm">
            <center>
                <img src="" class="rounded-circle" width=200px height=200px>
              </center>
          <br>
          <h3>Bimo Smartadi</h3>
          <h5>Co-Founder</h5>
        </div>

        <div class="col-sm skidip">
            <center>
                <img src="" class="rounded-circle" width=200px height=200px>
              </center>
          <br>
          <h3>Adli Daffa</h3>
          <h5>Chief Of Technology</h5>
        </div>

        <div class="col-sm">
            <center>
                <img src="" class="rounded-circle" width=200px height=200px>
              </center>
          <br>
          <h3 >Jasmine Nur Safiera</h3>
          <h5>Social Research <br><br><br><br></h5>
        </div>
      </div>
    </div>


    <br><br>



    <div class="container">
        {% if user.is_authenticated %}
        <br>
        <div class="row">
            <div class="col-md-6">
              <div class="col-md-12 text-center">
                <h5>Tuliskan komentar anda untuk kami!</h5>
                <br>
                <form action="{% url 'about:addComment' %}" method="POST">
                  {% csrf_token %}
                  {{form.testimoni_komentar}}
                  <input type="submit" value="Submit">
                </form>


              </div>
            </div>
        </div>

        {% else %}
          <div>
            <h5>Please Sign in before comment</h5>
          </div>

        {% endif %}
        

        {% if CommentUser %}
          <div id="CommentTerlihat">
            {% for testi in CommentUser %}
              <div>
                <tr>
                  <td>{{testi.comment}}</td>
                </tr>
              </div>
            {% endfor %}
            
          </div>
        {% else %}
        <div>
            <h5>No testimoni!</h5>
          </div>

        {% endif %}
          
  </div>






</body>
</html>