homepage/urls.py
from django.urls import path
from .views import home, logoutuser

app_name = 'homepage'

urlpatterns = [
    path('', home, name='home'),
    path('/logout/', logoutuser, name='logout'),
]

pepewrangers/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
import registerpage.urls as registerpageUrls
import landingpage.views as landingview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='landingpage/'), name='landingpage'),
    path('hello/', include('hello_world.urls')),
    path('landingpage/', include('landingpage.urls')),
    path('register/', include('registerpage.urls'), name='registerpage'),
    path('logout/', landingview.logoutuser, name = 'logout'),
    path('home/', include('homepage.urls')),
    path('programs/', include('programs.urls')),
    path('daftar_donasi/', include('daftar_donasi.urls'), name='daftar_donasi'),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('testimonipage/', include('testimonipage.urls')),

]

programs/urls.py
from django.urls import path
from .views import donation, index

app_name = 'programs'

urlpatterns = [
    path('<int:id>/', index, name='program'),
    path('donation/<int:id>', donation, name='donation')
]

programs/models.py
from django.db import models

# Create your models here.
class ProgramDonatur(models.Model):
    nama = models.CharField(max_length=255)
    donasi = models.IntegerField()
    
    def __str__(self):
        return self.nama

class ProgramDonasi(models.Model):
    nama = models.CharField(max_length=255)
    url_image = models.CharField(max_length=255)
    target = models.CharField(max_length=255)
    desc = models.TextField()
    terkumpul = models.IntegerField()
    donaturs = models.ManyToManyField(ProgramDonatur, blank=True)
    
    def __str__(self):
        return self.nama

programs/forms.py
from django import forms

class DonationForm(forms.Form):
    attrs = {
        'class': 'form-control',
    }
    nama = forms.CharField(label='Nama', max_length=255, required=True, widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(label='Email', max_length=255, required=True, widget=forms.EmailInput(attrs=attrs))
    donasi_attrs = {
        'class': 'form-control',
        'pattern': '[0-9]{1,9}',
    }
    donasi = forms.CharField(label='Jumlah Donasi', max_length=9, required=True, widget=forms.TextInput(attrs=donasi_attrs))
    anonymous = forms.BooleanField(label='', widget=forms.CheckboxInput(), required=False)

programs/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import DonationForm
from .models import ProgramDonasi, ProgramDonatur
from daftar_donasi.models import Donasi
from registerpage.models import Donatur

# Create your views here.
def index(request, id):
    program = ProgramDonasi.objects.get(id=id)
    donaturs = program.donaturs.all()
    donation_form = DonationForm
    response = {'donation_form': donation_form, 'program': program, 'donaturs': donaturs[::-1],
                    'count': donaturs.count()}
    return render(request, 'programs.html', response)

def donation(request, id):
    form = DonationForm(request.POST or None)
    form_email = request.POST['email']

    if(request.method == 'POST'
        and form.is_valid()
        and request.POST['donasi'].isdigit()
        and (Donatur.objects.filter(email=form_email).exists() or request.user.is_authenticated)):

        program = ProgramDonasi.objects.get(id=id)
        donasi = int(request.POST['donasi'])

        if('anonymous' not in request.POST):
            nama = request.POST['nama']
        else:
            nama = 'Fulan bin Fulan'

        donatur = ProgramDonatur(nama=nama, donasi=donasi)
        donatur.save()
        program.donaturs.add(donatur)
        program.terkumpul += donasi
        program.save()

        transaksi_donasi = Donasi(  nama_donatur=request.user.get_full_name(),
                                    email_donatur=request.user.email,
                                    nama_program=program.nama,
                                    jumlah_donasi=donasi)
        transaksi_donasi.save()

        return HttpResponseRedirect('/programs/'+str(id))
    else:
        return HttpResponseRedirect('/programs/'+str(id))

programs/templates/programs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Program Donasi</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">

</head>

<body id="main">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark" id="navigasi">
      <div class="container">
          <p class="navbar-brand" id="merek">Sinar Perak</p>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
                      <a class="nav-link navbar-text" href="/home/" id="home">Home
                          <span class="sr-only">(current)</span>
                      </a>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

  <div class="container">

    <div class="row">

      <div class="col-md-6">
        <br>
        <!-- Deskripsi Program -->
        <div class="mb-6">
          <img class="card-img-top" id="gambar" src={{program.url_image}} alt="gambar1">
          <div class="card-body">
            <h2 class="card-title" id="title">{{ program.nama }}</h2>
            <br>
            <h5 class="card-title">Target Pencapaian : Rp.{{ program.target }}</h5>
            <h5 class="card-title">Terkumpul : Rp.{{ program.terkumpul }}</h5>
            <br>
            <p class="card-text">{{ program.desc }}</p>
          </div>
        </div>
        <br><br>
      </div>

      <div class="col-md-6">
        <br>
        <!-- Form Donasi -->
        <div class="card my-6">
          <div class="card-body">
            <form id="form" method="POST" action="{% url 'programs:donation' id=program.id %}">
                {% csrf_token %}
                <div class="form-group">
                    {{ donation_form }}
                    <p>Centang untuk sembunyikan nama anda</p>
                </div>
            </form>
          </div>
        </div>

        <br>
        <div class="button">
          <button type="submit" class="btn btn-default" form="form" value="Submit">
            Saya mau ikut berdonasi !
          </button>
        </div>
        <br>

        <!-- Daftar Donatur -->
        <div class="card my-6">
          <h5 class="card-header">Daftar Donatur ({{count}} orang)</h5>
          <div class="card-body">
            <table class="table">
              <tbody>
                {% for donatur in donaturs %}
                <tr>
                  <td> {{donatur.nama}} </td>
                  <td> Rp.{{donatur.donasi}} </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <br>
      </div>

    </div>

  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
</body>

</html> 