homepage/urls.py
from django.urls import path
from .views import home, logoutuser

app_name = 'homepage'

urlpatterns = [
    path('', home, name='home'),
    path('/logout/', logoutuser, name='logout'),
]

pepewrangers/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView
import registerpage.urls as registerpageUrls
import landingpage.views as landingview
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='landingpage/'), name='landingpage'),
    path('hello/', include('hello_world.urls')),
    path('landingpage/', include('landingpage.urls')),
    path('register/', include('registerpage.urls'), name='registerpage'),
    path('logout/', landingview.logoutuser, name = 'logout'),
    path('home/', include('homepage.urls')),
    path('programs/', include('programs.urls')),
    path('daftar_donasi/', include('daftar_donasi.urls'), name='daftar_donasi'),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('testimonipage/', include('testimonipage.urls')),

]

programs/urls.py
from django.urls import path
from .views import donation, index

app_name = 'programs'

urlpatterns = [
    path('<int:id>/', index, name='program'),
    path('donation/<int:id>', donation, name='donation')
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from programs.models import ProgramDonasi
from registerpage.models import Donatur
# Create your views here.

#response = {}
def home(request):
        response = get_response()
        program = ProgramDonasi.objects.all()
        donatur = Donatur.objects.count()
        response['programlist'] = program
        response['JumlahDonatur'] = donatur
        return render(request, 'home.html', response)


def get_response():
    judul_1 = 'Mereka saat ini sangat membutuhkan uluran tanganmu,'
    judul_2 = 'Ayo bantu mereka !'
    nama = 'Sinar Perak'
    desc = 'Situs galang dana dan berdonasi secara terbuka bagi yang memerlukan'
    connect = 'Connect'
    email = ' sinarperak@gmail.com'
    cp = ' 081318405772 / Jasmine'
    response = {'judul_1':judul_1, 'judul_2':judul_2, 'nama':nama, 'desc':desc, 'connect':connect, 'email':email, 'cp': cp}
    return response


def logoutuser(request):
	logout(request)
	print('hehe')
	return HttpResponseRedirect('/landingpage/')

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Sinar Perak</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Charmonman" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    #gradasi {
        background-image: linear-gradient(#7d8b5a, #b5b173);

    }
    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
      height: 400px;
      overflow: hidden;
      padding: 0;
      border: 15;
      border-style: solid;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: black;
    }

    .img-fluid{
      width: 100%;
    }

    .judul1{
      font-weight: bold;
      font-size: 36px;
      font-family: 'Charmonman', cursive;
      color: black;
    }

    .judul2{
      font-weight: bold;
      font-size: 48px;
      font-family: 'Dosis', sans-serif;
      color: black;
    }
    .footer1{
      color: white;
      font-family: 'Dosis', sans-serif;
      font-size: 36px;
      padding: 25px;
    }
    .footer2{
      color: white;
      font-family: 'Dosis', sans-serif;
      font-size: 24px;
      padding: 25px;
    }
      .footer3{
        color: white;
        font-family: 'Dosis', sans-serif;
        font-size: 24px;
      }
      .backpanels{
        background: black;
      }
      .tulisan{
        color: white;
        font-family:'Dosis', sans-serif;
        font-size: 36px;
        text-align: center;
      }
      .top1{
        margin-top: 4px;
      }
  </style>
</head>
<body id = "gradasi">

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#">Sinar Perak</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/daftar_donasi/">Daftar Donasi</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/testimonipage/">Testimoni</a>
    </li>
    <li class="nav-item">
      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
       {% else %}
      <a class="nav-link" href="#">Log Out</a>
       {% endif %}
    </li>
  </ul>
</nav>

<div class="jumbotron" border="10"> <img src={% static "image/home1.jpg"%} style="background-size: 100vw;" class="img-fluid" alt="Responsive image">
  </div>


<br>
<br>
{% if user.is_authenticated %}
						<p class = "judul1 text-center">
							Halo, {{ user.first_name }} {{ user.last_name }}<br>
						</p>
					{% else %}
						<p class = "judul1 text-center">
							Halo<br>
						</p>
					{% endif %}

<p class = "judul1 text-center">{{judul_1}}</p>
<p class = "judul2 text-center">{{judul_2}}</p>

<div class="container">
   <h3 class="judul2 mt-3 pb-3 mb-4 font-italic border-bottom">
      List Program
   </h3>
   <div class="row">
     <<div class="card-deck">
     {% for news in programlist %}
      <div class="col-sm-12 col-md-6 col-lg-4 d-flex align-items-stretch top1">
         <div class="card">
            <img class="card-img-top img-responsive img-fluid" style="height: 176.34px;" src = {{news.url_image}} alt="Card image cap">
            <div class="card-body">
               <h5 class="card-title border-bottom pb-3">{{news.nama}}</h5>
                 {% if user.is_authenticated %}
                 <a href="{% url 'programs:program' id=news.id %}"><button type="button" class="btn btn-default text-align:center">Donasi</button></a>
                    {% else %}
                  <button type="button" class="myBtn btn btn-default text-align:center">Donasi</button>
                {% endif %}
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
    </div>


   </div>
   <hr>
</div>
<br>
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Login</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <p>You must Login
            <a href="{% url 'landingpage'  %}" role="button" class="btn btn-secondary popover-test" title="Popover title" data-content="Popover body content is set in this attribute.">Login</a></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>


<div class="container backpanels">
    <div class="panel backpanels">
      <p class="tulisan">Jumlah Donatur: </p>
      <p class='tulisan'>{{JumlahDonatur}} </p>


    </div>
</div>

  <footer>
    <div class="container-fluid" border="20">
      <div class="row">
        <div class = "col-sm-6">
          <p class = "footer1">{{nama}}</p>
          <p class = "footer2">{{desc}}</p>
        </div>
        <div class = "col-sm-6 ">
          <p class = "footer2">{{connect}}</p>
          <p class = 'footer3'><span class="fas fa-at"></span></span>{{email}}<p>
          <p class = 'footer3'><span class="fas fa-phone"></span>{{cp}}</p>
          </div>
          </div>
      </div>
</footer>

<script>
$(".myBtn").click(function(){
$(document).ready(function(){
        $("#myModal").modal();
    });
});
</script>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>